### PR TITLE
Adding .input-txt class selector to text input styling.

### PR DESCRIPTION
**Pull request by esimons**

### CODE REVIEW

**Comment by wylie** [comment]
Are we having issues with out the extra specificity?

**Comment by gjjones** [comment]
I get scared easily when we start throwing around element and type selectors. Do we really want this to target like that? It'll take more than a single class to override these styles after adding an attribute selector

**Comment by esimons** [comment]
Yeah, it's to address DE4878, which is that radio buttons in IE<=9 are showing a gray border. (The styling's there in modern browsers, too, but calculated border width is 0.)
image

**Comment by esimons** [comment]
Yeah, I know we're not fans of targeting elements, but given that it's already happening here, and it appears from the comment that it was always intended to target type "text", may as well, yeah?

**Comment by wylie** [comment]
Could we just target the radio buttons in order to remove the border?

**Comment by wylie** [comment]
Could we just target the radio buttons in order to remove the border?

Or perhaps we just need to add a class to this whole mess. Instead of `input` Maybe we add the class `.input-txt`. That would involve some work in Buzz so we actually have the class in widgets, but I don't think that would be a huge issue. 

Also, I think it's odd we haven't run into this issue until now. I can't imagine these are our first visible radio buttons.

**Comment by esimons** [comment]
They might be the first radio buttons that actually _look_ like radio buttons (I think dynamic tabs are actually radios?). Just checked and checkboxes apparently show same.

I'd probably vote for adding a class in Buzz. If we target a class, the result will be that the styling is opt-in only; whether that's seen as a pro or a con might be debatable, but since the class will come standard with the text-input widget, the issue would probably only arise if someone were creating a new composite widget that had text input controls coded directly into its handlebars template (in which case, who knows, maybe they don't want the standard styling applied).

**Comment by wylie** [comment]
I've read your comment a few times and for some reason it really isn't sinking in. I love when that happens. Brains are weird.

**Comment by esimons** [comment]
There's a PR up in BuzzFramework, and I've confirmed no custom widgets in any of our main interfaces use text inputs in their templates.

**Comment by esimons** [comment]
@wylie we cool to merge? I don't have write access.

**Comment by wylie** [comment]
Yep, I was just waiting to hear from you. I will merge it in now.

**Pull request merged**
