### PR TITLE
New Mixin

### PR DESCRIPTION
**Pull request by wylie**
Adding a mixin for columns- should help prevent them from looking stupid.

Columns were breaking at certain breakpoints. This should help fix that, so long as people use the mixin when they use CSS columns.

### CODE REVIEW

**Comment by caseytrombley** [comment]
Looks good to me. This is so the text never get's orphaned into the next column for no apparent reason, right?

**Comment by wylie** [comment]
@caseytrombley yes. it's a more complete, and some wishful thinking, set of properties.

**Comment by wylie** [comment]
@gjjones brain cat... removed them

**Comment by gjjones** [comment]
Much better! #approved with the assumption that this was tested and such beforehand. Safe assumption knowing you.

**Comment by wylie** [comment]
Testing...?

**Pull request merged**
