### PR TITLE
rename label to option-text to prevent clashing dropdowns and input f…

### PR DESCRIPTION
**Pull request by pivnickm**
rename label to option-text to prevent clashing dropdowns and input fields where other fields have labels on them.

### CODE REVIEW

**Comment by leachryanb** [comment]
@pivnickm This being a low-level frameworky thing, are you sure this doesn't kill anything else?

**Review by gjjones — APPROVED** [review]
cool beans!

**Comment by gjjones** [comment]
of course there's the obligatory, don't forget to check the other interfaces and such

**Comment by pivnickm** [comment]
Everything looks fine in NUP. I think the only other place the dropdown widget it used is the DMP Recent updates. 

How much do I need to look at the classic Buzz versions of EFSP and K5? I'm actually not sure if any of that is used anymore.

**Comment by EAE-BuildUser** [comment]
There is no more Buzz version of those interfaces, so you’re good. Only other would be nurc.

**Pull request merged**
