### PR TITLE
Remove Mixins #103

### PR DESCRIPTION
**Pull request by wylie**
This is a first pass at removing this mixin. More will be added to this PR. You have been warned!

### CODE REVIEW

**Comment by gjjones** [comment]
I'm liking it so far! :+1:

**Comment by wylie** [comment]
@gjjones was just going to ask if there were any others you saw that you think could come out

**Comment by gjjones** [comment]
Not off the top of my head, but I would like to consider autoprefixr for our prefixing needs. Can't remember if it'll handle the filter equivalents thought.

**Comment by wylie** [comment]
I'm down. Looks like there is a LESS version too: https://github.com/less/less-plugin-autoprefix

**Comment by wylie** [comment]
I'm really upping my delete numbers!

**Comment by gjjones** [comment]
thething

**Comment by wylie** [comment]
closes #87 also

**Pull request merged**
