### PR TITLE
Release no tag

### PR DESCRIPTION
**Pull request by leachryanb**
This adjusts edna's package.json, Makefile, Gruntfile and Jenkins build configs to support changes in the npm-preinstall and grunt-eis-release utils.

### CODE REVIEW

**Comment by wylie** [comment]
Looks a-okay to me. ~~I can go ahead and merge this in?~~ I will **not** merge this in!

**Comment by gjjones** [comment]
What's going on with this? Why not merge it?

**Comment by leachryanb** [comment]
Oh!  sorry.  Totes shoulda merged.  I'll git 'er done

**Comment by wylie** [comment]
@leachryanb are you done with the branch? Can we delete ( :scissors: ) it?

**Pull request merged**
