### PR TITLE
Remove coloring from bold class in release branch

### PR DESCRIPTION
**Pull request by amyh**

### CODE REVIEW

**Comment by gjjones** [comment]
Safe to assume this is for 15.4?

**Comment by wylie** [comment]
Yep, it's going into release

**Comment by wylie** [comment]
This color might not need to be in the `strong` declaration. I'm not a fan of using the `.bold` class in the markup. Can we use another strong tag and remove the `.bold` class? It's silly to use a class that markup can do better.

``` html
<p class="txt" data-auto="buzz-paragraph">
    You have viewed 
    <strong>1</strong>
    of <strong>10</strong>
    Free Topics. Sign up for a 
    <a class="bold" href="http://auth-qa.dynamed.com/webauth/login.aspx?trial-link">FREE 90 Day Trial</a>
    now. Already a subscriber? 
    <a class="bold" href="http://auth-qa.dynamed.com/webauth/login.aspx">Log In</a>.
</p>
```

**Comment by gjjones** [comment]
I'm going to agree from the consistency standpoint unless there's a very good reason why two things right next to each other would be using different styling methods.

**Comment by amyh** [comment]
I agree that it's better to be consistent. I still think the `.bold` class is preferable to `<strong>` in this context because I wouldn't say those phrases more loudly than the text around them, but maybe that's not my call.

**Comment by wylie** [comment]
Then it sounds like this is a perfect case for a `<b>` element.

In fact every use of the `.bold` class should be changed to a `<b>` element.

> Do not confuse the `<b>` element with the `<strong>`, `<em>`, or `<mark>` elements. The `<strong>` element represents text of certain importance, `<em>` puts some emphasis on the text and the `<mark>` element represents text of certain relevance. The `<b>` element doesn't convey such special semantic information; use it only when no others fit.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b

**Comment by amyh** [comment]
OK, so if I change all the tags to `<b>`, can we remove the color in the release branch?

**Comment by wylie** [comment]
~~So long as that doesn't cause any issues anywhere, this color has been in here for a while so some things might be looking for the color specified. Have you checked everything for uses of the `.bold` class and `<strong>` or `<b>` elements?~~

Never mind, will be merging in.

**Pull request merged**
