### PR TITLE
Remove kss

### PR DESCRIPTION
**Pull request by gjjones**

### CODE REVIEW

**Comment by wylie** [comment]
Awesome. Are you going to remove all the KSS comments from the top of the stylesheets too?

**Comment by gjjones** [comment]
Darn, should have done that here. Short answer yes. Long answer is yes, once I touch those files for this US.

**Comment by gjjones** [comment]
Good news is that you already went ahead and removed them in earlier commits. There was only a single one left in the form file, which is now removed!

**Comment by wylie** [comment]
Oh, awesome!

On Wed, Mar 23, 2016 at 4:20 AM -0700, "Greg Jones" <notifications@github.com<mailto:notifications@github.com>> wrote:

Good news is that you already went ahead and removed them. There was only a single one left in the form file, which is now removed!

##

**Comment by gjjones** [comment]
:+1:

**Pull request merged**
