### PR TITLE
GruntIcon 2.0

### PR DESCRIPTION
**Pull request by wylie**
**WIP**
_(no plans to merge yet, just getting this PR going just so we can remember where things are at)_

new version of GruntIcon. Went with `~2.0.0` because going with the latest version, `2.2.1`, caused errors when running `npm install`

/cc @gjjones

### CODE REVIEW

**Comment by gjjones** [comment]
I think Buzz uses it's own version of grunticon, right?

**Comment by EAE-BuildUser** [comment]
I would check our version of grunt-grunticon and update the hell outta that as well

**Comment by wylie** [comment]
I haven’t tested it yet. Wanted to get the PR going just so I remember where things are at. I don't have any plans to merge yet.

**Comment by gjjones** [comment]
Good thinking! Carry on

**Pull request closed without merging**
