### PR TITLE
making the breadcrumb non bold and adding padding bellow

### PR DESCRIPTION
**Pull request by JayBellew**

### CODE REVIEW

**Comment by amyh** [comment]
Who is fernstreet?

**Comment by LeopoldoFu** [comment]
I think that's Jay?

**Comment by JayBellew** [comment]
yup that's me (Jay)...working with Greg on that...he's going to review it

On Mon, Jun 27, 2016 at 12:42 PM, LeopoldoFu notifications@github.com
wrote:

> I think that's Jay?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ebsco/edna/pull/223#issuecomment-228802636, or mute
> the thread
> https://github.com/notifications/unsubscribe/AGOYCJ7vHzkZo8OEWiKN_kgzeslO0A58ks5qP_2JgaJpZM4I_QAE
> .

## 

Jay

**Comment by gjjones** [comment]
:+1:, nice job

**Pull request merged**
