### PR TITLE
Some Little Fixes

### PR DESCRIPTION
**Pull request by wylie**
adding a transition mixin so we can have all the browser prefixed properties. also cleaning up a transport mixin so when a transport is inactive it does nothing but sit there and wait for it to become active

### CODE REVIEW

**Comment by gjjones** [comment]
Is the `!important` due to specificity issues, or cause we just really want to enforce that style?

**Comment by wylie** [comment]
Yep, specificity issues. The transports need some cleaning up. They should also be using an SVG image for the arrow. Those are issues to tackle later though.

**Comment by gjjones** [comment]
Sounds good to me

**Comment by amyh** [comment]
I like the transition mixin -- great idea!

**Comment by gjjones** [comment]
Pushing this through to alleviate a build issue now since we all seem to approve. Please feel free to continue any discussion about this content.

**Comment by wylie** [comment]
Whoops, sorry about that. Thanks for merging

**Pull request merged**
