### PR TITLE
Brings in form styling for new modals into edna.

### PR DESCRIPTION
**Pull request by gjjones**
These styles might need to be propagated around and probably made the default styling since I think we're using this going forwards. Ryan P would know more.

### CODE REVIEW

**Comment by wylie** [comment]
👍🏻

**Comment by wylie** [comment]
We might need some documentation for this so others can start to use it.

**Comment by wylie** [comment]
@gjjones you good if this gets merged in?

**Comment by gjjones** [comment]
Yes. I'll get around to documentation once I get back full time.

**Comment by wylie** [comment]
No problem at all

**Pull request merged**
